/*
 * This file is generated by jOOQ.
 */
package com.example.jobserver.jooq.tables.pojos;


import com.example.jobserver.jooq.enums.JobsStatus;

import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.JSON;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Jobs implements Serializable {

    private static final long serialVersionUID = 1L;

    private String id;
    private Long userId;
    private Long projectId;
    private JobsStatus status;
    private JSON parameters;
    private JSON result;
    private String errorMessage;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public Jobs() {}

    public Jobs(Jobs value) {
        this.id = value.id;
        this.userId = value.userId;
        this.projectId = value.projectId;
        this.status = value.status;
        this.parameters = value.parameters;
        this.result = value.result;
        this.errorMessage = value.errorMessage;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public Jobs(
        String id,
        Long userId,
        Long projectId,
        JobsStatus status,
        JSON parameters,
        JSON result,
        String errorMessage,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.userId = userId;
        this.projectId = projectId;
        this.status = status;
        this.parameters = parameters;
        this.result = result;
        this.errorMessage = errorMessage;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>jobs.jobs.id</code>.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Setter for <code>jobs.jobs.id</code>.
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for <code>jobs.jobs.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>jobs.jobs.user_id</code>.
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>jobs.jobs.project_id</code>.
     */
    public Long getProjectId() {
        return this.projectId;
    }

    /**
     * Setter for <code>jobs.jobs.project_id</code>.
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * Getter for <code>jobs.jobs.status</code>.
     */
    public JobsStatus getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>jobs.jobs.status</code>.
     */
    public void setStatus(JobsStatus status) {
        this.status = status;
    }

    /**
     * Getter for <code>jobs.jobs.parameters</code>.
     */
    public JSON getParameters() {
        return this.parameters;
    }

    /**
     * Setter for <code>jobs.jobs.parameters</code>.
     */
    public void setParameters(JSON parameters) {
        this.parameters = parameters;
    }

    /**
     * Getter for <code>jobs.jobs.result</code>.
     */
    public JSON getResult() {
        return this.result;
    }

    /**
     * Setter for <code>jobs.jobs.result</code>.
     */
    public void setResult(JSON result) {
        this.result = result;
    }

    /**
     * Getter for <code>jobs.jobs.error_message</code>.
     */
    public String getErrorMessage() {
        return this.errorMessage;
    }

    /**
     * Setter for <code>jobs.jobs.error_message</code>.
     */
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    /**
     * Getter for <code>jobs.jobs.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>jobs.jobs.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>jobs.jobs.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>jobs.jobs.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Jobs other = (Jobs) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.projectId == null) {
            if (other.projectId != null)
                return false;
        }
        else if (!this.projectId.equals(other.projectId))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.parameters == null) {
            if (other.parameters != null)
                return false;
        }
        else if (!this.parameters.equals(other.parameters))
            return false;
        if (this.result == null) {
            if (other.result != null)
                return false;
        }
        else if (!this.result.equals(other.result))
            return false;
        if (this.errorMessage == null) {
            if (other.errorMessage != null)
                return false;
        }
        else if (!this.errorMessage.equals(other.errorMessage))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.projectId == null) ? 0 : this.projectId.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.parameters == null) ? 0 : this.parameters.hashCode());
        result = prime * result + ((this.result == null) ? 0 : this.result.hashCode());
        result = prime * result + ((this.errorMessage == null) ? 0 : this.errorMessage.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Jobs (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(projectId);
        sb.append(", ").append(status);
        sb.append(", ").append(parameters);
        sb.append(", ").append(result);
        sb.append(", ").append(errorMessage);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
