/*
 * This file is generated by jOOQ.
 */
package com.example.jobserver.jooq.tables;


import com.example.jobserver.jooq.Indexes;
import com.example.jobserver.jooq.Keys;
import com.example.jobserver.jooq.enums.JobsStatus;
import com.example.jobserver.jooq.tables.Projects.ProjectsPath;
import com.example.jobserver.jooq.tables.Users.UsersPath;
import com.example.jobserver.jooq.tables.records.JobsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSON;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Jobs extends TableImpl<JobsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>jobs.jobs</code>
     */
    public static final Jobs JOBS_ = new Jobs();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JobsRecord> getRecordType() {
        return JobsRecord.class;
    }

    /**
     * The column <code>jobs.jobs.id</code>.
     */
    public final TableField<JobsRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>jobs.jobs.user_id</code>.
     */
    public final TableField<JobsRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>jobs.jobs.project_id</code>.
     */
    public final TableField<JobsRecord, Long> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>jobs.jobs.status</code>.
     */
    public final TableField<JobsRecord, JobsStatus> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(10).nullable(false).asEnumDataType(JobsStatus.class), this, "");

    /**
     * The column <code>jobs.jobs.parameters</code>.
     */
    public final TableField<JobsRecord, JSON> PARAMETERS = createField(DSL.name("parameters"), SQLDataType.JSON.nullable(false), this, "");

    /**
     * The column <code>jobs.jobs.result</code>.
     */
    public final TableField<JobsRecord, JSON> RESULT = createField(DSL.name("result"), SQLDataType.JSON, this, "");

    /**
     * The column <code>jobs.jobs.error_message</code>.
     */
    public final TableField<JobsRecord, String> ERROR_MESSAGE = createField(DSL.name("error_message"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>jobs.jobs.created_at</code>.
     */
    public final TableField<JobsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>jobs.jobs.updated_at</code>.
     */
    public final TableField<JobsRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private Jobs(Name alias, Table<JobsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Jobs(Name alias, Table<JobsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>jobs.jobs</code> table reference
     */
    public Jobs(String alias) {
        this(DSL.name(alias), JOBS_);
    }

    /**
     * Create an aliased <code>jobs.jobs</code> table reference
     */
    public Jobs(Name alias) {
        this(alias, JOBS_);
    }

    /**
     * Create a <code>jobs.jobs</code> table reference
     */
    public Jobs() {
        this(DSL.name("jobs"), null);
    }

    public <O extends Record> Jobs(Table<O> path, ForeignKey<O, JobsRecord> childPath, InverseForeignKey<O, JobsRecord> parentPath) {
        super(path, childPath, parentPath, JOBS_);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class JobsPath extends Jobs implements Path<JobsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> JobsPath(Table<O> path, ForeignKey<O, JobsRecord> childPath, InverseForeignKey<O, JobsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private JobsPath(Name alias, Table<JobsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public JobsPath as(String alias) {
            return new JobsPath(DSL.name(alias), this);
        }

        @Override
        public JobsPath as(Name alias) {
            return new JobsPath(alias, this);
        }

        @Override
        public JobsPath as(Table<?> alias) {
            return new JobsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : com.example.jobserver.jooq.Jobs.JOBS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.JOBS_PROJECT_ID, Indexes.JOBS_USER_ID);
    }

    @Override
    public UniqueKey<JobsRecord> getPrimaryKey() {
        return Keys.KEY_JOBS_PRIMARY;
    }

    @Override
    public List<ForeignKey<JobsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.JOBS_IBFK_1, Keys.JOBS_IBFK_2);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>jobs.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.JOBS_IBFK_1, null);

        return _users;
    }

    private transient ProjectsPath _projects;

    /**
     * Get the implicit join path to the <code>jobs.projects</code> table.
     */
    public ProjectsPath projects() {
        if (_projects == null)
            _projects = new ProjectsPath(this, Keys.JOBS_IBFK_2, null);

        return _projects;
    }

    @Override
    public Jobs as(String alias) {
        return new Jobs(DSL.name(alias), this);
    }

    @Override
    public Jobs as(Name alias) {
        return new Jobs(alias, this);
    }

    @Override
    public Jobs as(Table<?> alias) {
        return new Jobs(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Jobs rename(String name) {
        return new Jobs(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Jobs rename(Name name) {
        return new Jobs(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Jobs rename(Table<?> name) {
        return new Jobs(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Jobs where(Condition condition) {
        return new Jobs(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Jobs where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Jobs where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Jobs where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Jobs where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Jobs where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Jobs where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Jobs where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Jobs whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Jobs whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
