/*
 * This file is generated by jOOQ.
 */
package com.example.jobserver.jooq.tables;


import com.example.jobserver.jooq.Jobs;
import com.example.jobserver.jooq.Keys;
import com.example.jobserver.jooq.tables.Jobs.JobsPath;
import com.example.jobserver.jooq.tables.records.ProjectsRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Projects extends TableImpl<ProjectsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>jobs.projects</code>
     */
    public static final Projects PROJECTS = new Projects();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProjectsRecord> getRecordType() {
        return ProjectsRecord.class;
    }

    /**
     * The column <code>jobs.projects.id</code>.
     */
    public final TableField<ProjectsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>jobs.projects.name</code>.
     */
    public final TableField<ProjectsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(200).nullable(false), this, "");

    private Projects(Name alias, Table<ProjectsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Projects(Name alias, Table<ProjectsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>jobs.projects</code> table reference
     */
    public Projects(String alias) {
        this(DSL.name(alias), PROJECTS);
    }

    /**
     * Create an aliased <code>jobs.projects</code> table reference
     */
    public Projects(Name alias) {
        this(alias, PROJECTS);
    }

    /**
     * Create a <code>jobs.projects</code> table reference
     */
    public Projects() {
        this(DSL.name("projects"), null);
    }

    public <O extends Record> Projects(Table<O> path, ForeignKey<O, ProjectsRecord> childPath, InverseForeignKey<O, ProjectsRecord> parentPath) {
        super(path, childPath, parentPath, PROJECTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ProjectsPath extends Projects implements Path<ProjectsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ProjectsPath(Table<O> path, ForeignKey<O, ProjectsRecord> childPath, InverseForeignKey<O, ProjectsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ProjectsPath(Name alias, Table<ProjectsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ProjectsPath as(String alias) {
            return new ProjectsPath(DSL.name(alias), this);
        }

        @Override
        public ProjectsPath as(Name alias) {
            return new ProjectsPath(alias, this);
        }

        @Override
        public ProjectsPath as(Table<?> alias) {
            return new ProjectsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Jobs.JOBS;
    }

    @Override
    public Identity<ProjectsRecord, Long> getIdentity() {
        return (Identity<ProjectsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ProjectsRecord> getPrimaryKey() {
        return Keys.KEY_PROJECTS_PRIMARY;
    }

    private transient JobsPath _jobs;

    /**
     * Get the implicit to-many join path to the <code>jobs.jobs</code> table
     */
    public JobsPath jobs() {
        if (_jobs == null)
            _jobs = new JobsPath(this, null, Keys.JOBS_IBFK_2.getInverseKey());

        return _jobs;
    }

    @Override
    public Projects as(String alias) {
        return new Projects(DSL.name(alias), this);
    }

    @Override
    public Projects as(Name alias) {
        return new Projects(alias, this);
    }

    @Override
    public Projects as(Table<?> alias) {
        return new Projects(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Projects rename(String name) {
        return new Projects(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Projects rename(Name name) {
        return new Projects(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Projects rename(Table<?> name) {
        return new Projects(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Projects where(Condition condition) {
        return new Projects(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Projects where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Projects where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Projects where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Projects where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Projects where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Projects where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Projects where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Projects whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Projects whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
