/*
 * This file is generated by jOOQ.
 */
package com.example.jobserver.jooq.tables.daos;


import com.example.jobserver.jooq.enums.JobsStatus;
import com.example.jobserver.jooq.tables.Jobs;
import com.example.jobserver.jooq.tables.records.JobsRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.JSON;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JobsDao extends DAOImpl<JobsRecord, com.example.jobserver.jooq.tables.pojos.Jobs, String> {

    /**
     * Create a new JobsDao without any configuration
     */
    public JobsDao() {
        super(Jobs.JOBS_, com.example.jobserver.jooq.tables.pojos.Jobs.class);
    }

    /**
     * Create a new JobsDao with an attached configuration
     */
    public JobsDao(Configuration configuration) {
        super(Jobs.JOBS_, com.example.jobserver.jooq.tables.pojos.Jobs.class, configuration);
    }

    @Override
    public String getId(com.example.jobserver.jooq.tables.pojos.Jobs object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.example.jobserver.jooq.tables.pojos.Jobs> fetchRangeOfId(String lowerInclusive, String upperInclusive) {
        return fetchRange(Jobs.JOBS_.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.example.jobserver.jooq.tables.pojos.Jobs> fetchById(String... values) {
        return fetch(Jobs.JOBS_.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.example.jobserver.jooq.tables.pojos.Jobs fetchOneById(String value) {
        return fetchOne(Jobs.JOBS_.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.example.jobserver.jooq.tables.pojos.Jobs> fetchOptionalById(String value) {
        return fetchOptional(Jobs.JOBS_.ID, value);
    }

    /**
     * Fetch records that have <code>user_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.example.jobserver.jooq.tables.pojos.Jobs> fetchRangeOfUserId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Jobs.JOBS_.USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.example.jobserver.jooq.tables.pojos.Jobs> fetchByUserId(Long... values) {
        return fetch(Jobs.JOBS_.USER_ID, values);
    }

    /**
     * Fetch records that have <code>project_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.example.jobserver.jooq.tables.pojos.Jobs> fetchRangeOfProjectId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Jobs.JOBS_.PROJECT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>project_id IN (values)</code>
     */
    public List<com.example.jobserver.jooq.tables.pojos.Jobs> fetchByProjectId(Long... values) {
        return fetch(Jobs.JOBS_.PROJECT_ID, values);
    }

    /**
     * Fetch records that have <code>status BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.example.jobserver.jooq.tables.pojos.Jobs> fetchRangeOfStatus(JobsStatus lowerInclusive, JobsStatus upperInclusive) {
        return fetchRange(Jobs.JOBS_.STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.example.jobserver.jooq.tables.pojos.Jobs> fetchByStatus(JobsStatus... values) {
        return fetch(Jobs.JOBS_.STATUS, values);
    }

    /**
     * Fetch records that have <code>parameters BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.example.jobserver.jooq.tables.pojos.Jobs> fetchRangeOfParameters(JSON lowerInclusive, JSON upperInclusive) {
        return fetchRange(Jobs.JOBS_.PARAMETERS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>parameters IN (values)</code>
     */
    public List<com.example.jobserver.jooq.tables.pojos.Jobs> fetchByParameters(JSON... values) {
        return fetch(Jobs.JOBS_.PARAMETERS, values);
    }

    /**
     * Fetch records that have <code>result BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.example.jobserver.jooq.tables.pojos.Jobs> fetchRangeOfResult(JSON lowerInclusive, JSON upperInclusive) {
        return fetchRange(Jobs.JOBS_.RESULT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>result IN (values)</code>
     */
    public List<com.example.jobserver.jooq.tables.pojos.Jobs> fetchByResult(JSON... values) {
        return fetch(Jobs.JOBS_.RESULT, values);
    }

    /**
     * Fetch records that have <code>error_message BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.example.jobserver.jooq.tables.pojos.Jobs> fetchRangeOfErrorMessage(String lowerInclusive, String upperInclusive) {
        return fetchRange(Jobs.JOBS_.ERROR_MESSAGE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>error_message IN (values)</code>
     */
    public List<com.example.jobserver.jooq.tables.pojos.Jobs> fetchByErrorMessage(String... values) {
        return fetch(Jobs.JOBS_.ERROR_MESSAGE, values);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.example.jobserver.jooq.tables.pojos.Jobs> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Jobs.JOBS_.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.example.jobserver.jooq.tables.pojos.Jobs> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(Jobs.JOBS_.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>updated_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.example.jobserver.jooq.tables.pojos.Jobs> fetchRangeOfUpdatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Jobs.JOBS_.UPDATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<com.example.jobserver.jooq.tables.pojos.Jobs> fetchByUpdatedAt(LocalDateTime... values) {
        return fetch(Jobs.JOBS_.UPDATED_AT, values);
    }
}
