/*
 * This file is generated by jOOQ.
 */
package com.example.jobserver.jooq.tables.daos;


import com.example.jobserver.jooq.tables.Projects;
import com.example.jobserver.jooq.tables.records.ProjectsRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProjectsDao extends DAOImpl<ProjectsRecord, com.example.jobserver.jooq.tables.pojos.Projects, Long> {

    /**
     * Create a new ProjectsDao without any configuration
     */
    public ProjectsDao() {
        super(Projects.PROJECTS, com.example.jobserver.jooq.tables.pojos.Projects.class);
    }

    /**
     * Create a new ProjectsDao with an attached configuration
     */
    public ProjectsDao(Configuration configuration) {
        super(Projects.PROJECTS, com.example.jobserver.jooq.tables.pojos.Projects.class, configuration);
    }

    @Override
    public Long getId(com.example.jobserver.jooq.tables.pojos.Projects object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.example.jobserver.jooq.tables.pojos.Projects> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Projects.PROJECTS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.example.jobserver.jooq.tables.pojos.Projects> fetchById(Long... values) {
        return fetch(Projects.PROJECTS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.example.jobserver.jooq.tables.pojos.Projects fetchOneById(Long value) {
        return fetchOne(Projects.PROJECTS.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.example.jobserver.jooq.tables.pojos.Projects> fetchOptionalById(Long value) {
        return fetchOptional(Projects.PROJECTS.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.example.jobserver.jooq.tables.pojos.Projects> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Projects.PROJECTS.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.example.jobserver.jooq.tables.pojos.Projects> fetchByName(String... values) {
        return fetch(Projects.PROJECTS.NAME, values);
    }
}
