/*
 * This file is generated by jOOQ.
 */
package com.example.jobserver.jooq.tables.records;


import com.example.jobserver.jooq.enums.JobsStatus;
import com.example.jobserver.jooq.tables.Jobs;

import java.time.LocalDateTime;

import org.jooq.JSON;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JobsRecord extends UpdatableRecordImpl<JobsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>jobs.jobs.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>jobs.jobs.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>jobs.jobs.user_id</code>.
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>jobs.jobs.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>jobs.jobs.project_id</code>.
     */
    public void setProjectId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>jobs.jobs.project_id</code>.
     */
    public Long getProjectId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>jobs.jobs.status</code>.
     */
    public void setStatus(JobsStatus value) {
        set(3, value);
    }

    /**
     * Getter for <code>jobs.jobs.status</code>.
     */
    public JobsStatus getStatus() {
        return (JobsStatus) get(3);
    }

    /**
     * Setter for <code>jobs.jobs.parameters</code>.
     */
    public void setParameters(JSON value) {
        set(4, value);
    }

    /**
     * Getter for <code>jobs.jobs.parameters</code>.
     */
    public JSON getParameters() {
        return (JSON) get(4);
    }

    /**
     * Setter for <code>jobs.jobs.result</code>.
     */
    public void setResult(JSON value) {
        set(5, value);
    }

    /**
     * Getter for <code>jobs.jobs.result</code>.
     */
    public JSON getResult() {
        return (JSON) get(5);
    }

    /**
     * Setter for <code>jobs.jobs.error_message</code>.
     */
    public void setErrorMessage(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>jobs.jobs.error_message</code>.
     */
    public String getErrorMessage() {
        return (String) get(6);
    }

    /**
     * Setter for <code>jobs.jobs.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>jobs.jobs.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>jobs.jobs.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>jobs.jobs.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JobsRecord
     */
    public JobsRecord() {
        super(Jobs.JOBS_);
    }

    /**
     * Create a detached, initialised JobsRecord
     */
    public JobsRecord(String id, Long userId, Long projectId, JobsStatus status, JSON parameters, JSON result, String errorMessage, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Jobs.JOBS_);

        setId(id);
        setUserId(userId);
        setProjectId(projectId);
        setStatus(status);
        setParameters(parameters);
        setResult(result);
        setErrorMessage(errorMessage);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised JobsRecord
     */
    public JobsRecord(com.example.jobserver.jooq.tables.pojos.Jobs value) {
        super(Jobs.JOBS_);

        if (value != null) {
            setId(value.getId());
            setUserId(value.getUserId());
            setProjectId(value.getProjectId());
            setStatus(value.getStatus());
            setParameters(value.getParameters());
            setResult(value.getResult());
            setErrorMessage(value.getErrorMessage());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetChangedOnNotNull();
        }
    }
}
