/*
 * This file is generated by jOOQ.
 */
package com.example.jobserver.jooq;


import com.example.jobserver.jooq.tables.FlywaySchemaHistory;
import com.example.jobserver.jooq.tables.Jobs;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in jobs.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FLYWAY_SCHEMA_HISTORY_FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex(DSL.name("flyway_schema_history_s_idx"), FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
    public static final Index JOBS_PROJECT_ID = Internal.createIndex(DSL.name("project_id"), Jobs.JOBS_, new OrderField[] { Jobs.JOBS_.PROJECT_ID }, false);
    public static final Index JOBS_USER_ID = Internal.createIndex(DSL.name("user_id"), Jobs.JOBS_, new OrderField[] { Jobs.JOBS_.USER_ID }, false);
}
