/*
 * This file is generated by jOOQ.
 */
package com.example.jobserver.jooq;


import com.example.jobserver.jooq.tables.FlywaySchemaHistory;
import com.example.jobserver.jooq.tables.Projects;
import com.example.jobserver.jooq.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Jobs extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>jobs</code>
     */
    public static final Jobs JOBS = new Jobs();

    /**
     * The table <code>jobs.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>jobs.jobs</code>.
     */
    public final com.example.jobserver.jooq.tables.Jobs JOBS_ = com.example.jobserver.jooq.tables.Jobs.JOBS_;

    /**
     * The table <code>jobs.projects</code>.
     */
    public final Projects PROJECTS = Projects.PROJECTS;

    /**
     * The table <code>jobs.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Jobs() {
        super("jobs", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            com.example.jobserver.jooq.tables.Jobs.JOBS_,
            Projects.PROJECTS,
            Users.USERS
        );
    }
}
