/*
 * This file is generated by jOOQ.
 */
package com.example.jobserver.jooq;


import com.example.jobserver.jooq.tables.FlywaySchemaHistory;
import com.example.jobserver.jooq.tables.Jobs;
import com.example.jobserver.jooq.tables.Projects;
import com.example.jobserver.jooq.tables.Users;
import com.example.jobserver.jooq.tables.records.FlywaySchemaHistoryRecord;
import com.example.jobserver.jooq.tables.records.JobsRecord;
import com.example.jobserver.jooq.tables.records.ProjectsRecord;
import com.example.jobserver.jooq.tables.records.UsersRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * jobs.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FlywaySchemaHistoryRecord> KEY_FLYWAY_SCHEMA_HISTORY_PRIMARY = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("KEY_flyway_schema_history_PRIMARY"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<JobsRecord> KEY_JOBS_PRIMARY = Internal.createUniqueKey(Jobs.JOBS_, DSL.name("KEY_jobs_PRIMARY"), new TableField[] { Jobs.JOBS_.ID }, true);
    public static final UniqueKey<ProjectsRecord> KEY_PROJECTS_PRIMARY = Internal.createUniqueKey(Projects.PROJECTS, DSL.name("KEY_projects_PRIMARY"), new TableField[] { Projects.PROJECTS.ID }, true);
    public static final UniqueKey<UsersRecord> KEY_USERS_EMAIL = Internal.createUniqueKey(Users.USERS, DSL.name("KEY_users_email"), new TableField[] { Users.USERS.EMAIL }, true);
    public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = Internal.createUniqueKey(Users.USERS, DSL.name("KEY_users_PRIMARY"), new TableField[] { Users.USERS.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<JobsRecord, UsersRecord> JOBS_IBFK_1 = Internal.createForeignKey(Jobs.JOBS_, DSL.name("jobs_ibfk_1"), new TableField[] { Jobs.JOBS_.USER_ID }, Keys.KEY_USERS_PRIMARY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<JobsRecord, ProjectsRecord> JOBS_IBFK_2 = Internal.createForeignKey(Jobs.JOBS_, DSL.name("jobs_ibfk_2"), new TableField[] { Jobs.JOBS_.PROJECT_ID }, Keys.KEY_PROJECTS_PRIMARY, new TableField[] { Projects.PROJECTS.ID }, true);
}
