/*
 * This file is generated by jOOQ.
 */
package com.example.jobserver.jooq;


import com.example.jobserver.jooq.tables.FlywaySchemaHistory;
import com.example.jobserver.jooq.tables.Jobs;
import com.example.jobserver.jooq.tables.Projects;
import com.example.jobserver.jooq.tables.Users;


/**
 * Convenience access to all tables in jobs.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>jobs.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>jobs.jobs</code>.
     */
    public static final Jobs JOBS_ = Jobs.JOBS_;

    /**
     * The table <code>jobs.projects</code>.
     */
    public static final Projects PROJECTS = Projects.PROJECTS;

    /**
     * The table <code>jobs.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
